import './css/style.css'

import Theme from './theme-provider'
import AppProvider from './app-provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>{/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body className="font-sans antialiased bg-gray-100 dark:bg-gray-900 text-gray-600 dark:text-gray-400" style={{ fontFamily: 'system-ui, -apple-system, sans-serif' }}>
        <Theme>
          <AppProvider>
            {children}
          </AppProvider>
        </Theme>
      </body>
    </html>
  )
}
